spring:
  application:
    name: study

  datasource:
    url: jdbc:mysql://localhost:3306/boarddb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    root: INFO
    com.springboot.study: DEBUG
